# Generated by Django 4.1.3 on 2023-01-03 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Kod pocztowy musi być w formacie 'xx-xxx'",
                        regex="^\\d{2}-\\d{3}$",
                    )
                ],
                verbose_name="Kod pocztowy",
            ),
        ),
    ]
